Auth:
  license: "" #license key
Server:
  Name: "Hex Web" #server name
  Port: 3100  #server port
Email:
  SendGridToken: "" #sendgrid token
  fromEmail: "" #from email
  ToEmail: "" #to email
Store:
  Products:
    - name: "Hex AI"
      price: 10.99
      image: "/Store/Product.png"
      link: "https://hexmodz.com/"
    - name: "Vortex Engine"
      price: 15.00
      image: "/Store/Product.png"
      link: "https://hexmodz.com/"
    - name: "Server Boost"
      price: 20.00
      image: "/Store/Product.png"
      link: "https://hexmodz.com/"
